name: Light House
on: 
  push: 
    branches: 
      - develop

jobs: 
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Dependencies
        run: npm add @unlighthouse/cli puppeteer
        
      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site https://fluma-lfals-fluma.vercel.app --budget 75 --build-static
